import { NESHeader, NESGraphicsData } from '../types/nes';
import { serializeNESHeader } from './nesHeader';

export function generateCHeader(graphics: NESGraphicsData, header: NESHeader): string {
  const headerBytes = serializeNESHeader(header);
  const hexBytes = (bytes: Uint8Array, indent = '  ', perLine = 16) => {
    let result = '';
    for (let i = 0; i < bytes.length; i++) {
      if (i % perLine === 0) result += indent;
      result += '0x' + bytes[i].toString(16).padStart(2, '0').toUpperCase();
      if (i < bytes.length - 1) result += ', ';
      if ((i + 1) % perLine === 0 || i === bytes.length - 1) result += '\n';
    }
    return result;
  };

  const palBytes = new Uint8Array(16);
  for (let s = 0; s < 4; s++) {
    for (let c = 0; c < 4; c++) {
      palBytes[s * 4 + c] = graphics.subPalettes[s].colors[c];
    }
  }

  return `/*
 * NES Graphics & Header Assets
 * Generated by NES ROM & Header Studio
 * Target: cc65 / neslib / 8bitworkshop
 */

#ifndef NES_ASSETS_H
#define NES_ASSETS_H

// 16-byte iNES / NES 2.0 ROM Header
const unsigned char NES_HEADER[16] = {
${hexBytes(headerBytes)}
};

// Background Palette (16 bytes: 4 subpalettes x 4 colors)
const unsigned char PALETTE_DATA[16] = {
${hexBytes(palBytes)}
};

// Nametable (960 bytes: 32x30 tile indices)
const unsigned char NAMETABLE_DATA[960] = {
${hexBytes(graphics.nametable.subarray(0, 960), '  ', 16)}
};

// Attribute Table (64 bytes: 16x16 macroblock palette assignment)
const unsigned char ATTRIBUTE_DATA[64] = {
${hexBytes(graphics.attributeTable.subarray(0, 64), '  ', 16)}
};

// CHR Pattern Table (First ${graphics.uniqueTilesCount} unique tiles, 16 bytes/tile)
// Total bytes: ${graphics.uniqueTilesCount * 16}
const unsigned char CHR_DATA[${Math.max(16, graphics.uniqueTilesCount * 16)}] = {
${hexBytes(graphics.patternTable.subarray(0, graphics.uniqueTilesCount * 16), '  ', 16)}
};

#endif // NES_ASSETS_H
`;
}

export function generateAsmCode(graphics: NESGraphicsData, header: NESHeader): string {
  const headerBytes = serializeNESHeader(header);
  const asmBytes = (bytes: Uint8Array, label: string, perLine = 16) => {
    let result = `${label}:\n`;
    for (let i = 0; i < bytes.length; i++) {
      if (i % perLine === 0) result += '  .byte ';
      result += '$' + bytes[i].toString(16).padStart(2, '0').toUpperCase();
      if ((i + 1) % perLine === 0 || i === bytes.length - 1) {
        result += '\n';
      } else {
        result += ', ';
      }
    }
    return result;
  };

  const palBytes = new Uint8Array(16);
  for (let s = 0; s < 4; s++) {
    for (let c = 0; c < 4; c++) {
      palBytes[s * 4 + c] = graphics.subPalettes[s].colors[c];
    }
  }

  return `; ====================================================================
; NES 6502 Assembly Assets (ca65 / asm6 / nesasm)
; Generated by NES ROM & Header Studio
; ====================================================================

; 16-byte iNES / NES 2.0 Header
${asmBytes(headerBytes, 'ines_header')}

; 16-byte Background Palette (PPU $3F00)
${asmBytes(palBytes, 'palette_bg')}

; 960-byte Nametable Data
${asmBytes(graphics.nametable.subarray(0, 960), 'nametable_data')}

; 64-byte Attribute Table Data
${asmBytes(graphics.attributeTable.subarray(0, 64), 'attribute_data')}

; CHR Pattern Data (${graphics.uniqueTilesCount} tiles)
${asmBytes(graphics.patternTable.subarray(0, graphics.uniqueTilesCount * 16), 'chr_data')}
`;
}

export function generateHexDump(bytes: Uint8Array, perLine = 16): string {
  let output = '';
  for (let i = 0; i < bytes.length; i += perLine) {
    const chunk = bytes.subarray(i, Math.min(i + perLine, bytes.length));
    const offset = i.toString(16).padStart(4, '0').toUpperCase();

    // Hex part
    const hexParts: string[] = [];
    for (let j = 0; j < perLine; j++) {
      if (j < chunk.length) {
        hexParts.push(chunk[j].toString(16).padStart(2, '0').toUpperCase());
      } else {
        hexParts.push('  ');
      }
    }

    // ASCII part
    let asciiPart = '';
    for (let j = 0; j < chunk.length; j++) {
      const b = chunk[j];
      asciiPart += (b >= 32 && b <= 126) ? String.fromCharCode(b) : '.';
    }

    output += `${offset}:  ${hexParts.slice(0, 8).join(' ')}  ${hexParts.slice(8).join(' ')}  |${asciiPart}|\n`;
  }
  return output;
}
